# -*- coding: utf-8 -*-
r"""Generate the manuscript's ontology-metrics table directly from OnSIR.ttl.

The table used to be maintained by hand and had drifted from the artifact (it reported the
disjointness and restriction counts of an earlier build). Counting here means the table cannot
disagree with the release it describes.

Counting rules, stated because every one of them is a choice:
  * named classes / properties: IRIs in the OnSIR namespace only, so anonymous class expressions
    and imported terms are excluded;
  * disjointness axioms: owl:AllDisjointClasses nodes plus owl:disjointWith pairs;
  * restrictions: owl:Restriction nodes, split by the operator they carry, since "existential and
    cardinality" is narrower than "all restrictions";
  * external alignments: triples whose subject is an OnSIR IRI and whose object is an external
    class IRI, counted as triples and as distinct targets, which are different numbers.

Writes: paper/tab_metrics.tex
Run:    python make_metrics.py
"""
import os
from collections import Counter
import rdflib
from rdflib import RDF, RDFS, OWL, URIRef

NS = "https://w3id.org/onsir/"
OBO = "http://purl.obolibrary.org/obo/"
QUDT_UNIT = "http://qudt.org/vocab/unit/"

g = rdflib.Graph()
g.parse("OnSIR.ttl", format="turtle")


def named(t):
    return sorted(x for x in set(g.subjects(RDF.type, t))
                  if isinstance(x, URIRef) and str(x).startswith(NS))


R = set(g.subjects(RDF.type, OWL.Restriction))
sv = [r for r in R if (r, OWL.someValuesFrom, None) in g]
hv = [r for r in R if (r, OWL.hasValue, None) in g]
qc = [r for r in R if (r, OWL.qualifiedCardinality, None) in g
      or (r, OWL.minQualifiedCardinality, None) in g]

disj = len(set(g.subjects(RDF.type, OWL.AllDisjointClasses))) + \
    len(set(g.subject_objects(OWL.disjointWith)))

align = set()
for s, p, o in g:
    if (isinstance(s, URIRef) and str(s).startswith(NS)
            and isinstance(o, URIRef) and (str(o).startswith(OBO) or str(o).startswith(QUDT_UNIT))
            and not str(o).endswith("rbo.owl")):
        align.add((str(p), str(o)))
targets = {o for _, o in align}
fams = Counter()
for o in targets:
    fams[o[len(OBO):].split("_")[0] if o.startswith(OBO) else "QUDT"] += 1

# nominals (owl:hasValue) push the expressivity past ALCQI(D)
expr = r"$\mathcal{ALCOQI}(\mathcal{D})$" if hv else r"$\mathcal{ALCQI}(\mathcal{D})$"

rows = [
    ("Named classes", len(named(OWL.Class))),
    ("Object properties", len(named(OWL.ObjectProperty))),
    ("Datatype properties", len(named(OWL.DatatypeProperty))),
    ("Functional properties", len([x for x in set(g.subjects(RDF.type, OWL.FunctionalProperty))
                                   if str(x).startswith(NS)])),
    ("Disjointness axioms", disj),
    ("Existential and cardinality restrictions", len(sv) + len(qc)),
    (r"Nominal (\texttt{hasValue}) restrictions", len(hv)),
    ("Equivalences (covering, defined and dose-window classes)",
     len(set(g.subject_objects(OWL.equivalentClass)))),
    ("External alignment triples", len(align)),
    ("Distinct external terms aligned to", len(targets)),
]

body = "\n".join(f"{k} & {v}\\\\" for k, v in rows)
tab = r"""% GENERATED by make_metrics.py -- do not edit
\begin{table}[t]\centering
\caption{Size and expressivity of the release, counted from \texttt{OnSIR.ttl} by
\texttt{make\_metrics.py}. Counts cover the OnSIR namespace only, so imported terms and anonymous
class expressions are excluded. Alignment triples and distinct external terms are reported
separately because one external term can be the target of more than one triple.}
\label{tab:metrics}
\begin{tabular}{lr}
\toprule
@@BODY@@
DL expressivity & @@EXPR@@\\
Reasoner-checked (HermiT) & yes\\
\bottomrule
\end{tabular}
\end{table}
""".replace("@@BODY@@", body).replace("@@EXPR@@", expr)

with open(os.path.join("paper", "tab_metrics.tex"), "w") as fh:
    fh.write(tab)
print("wrote paper/tab_metrics.tex")
for k, v in rows:
    print(f"  {k:56s} {v}")
print(f"  expressivity: {expr}")
print(f"  external families: {dict(sorted(fams.items()))}")
